---
# Source: cartridge/templates/cluster.yaml
apiVersion: tarantool.io/v1beta1
kind: Cluster
metadata:
  name: my-cartridge
  labels:
    app.kubernetes.io/name: cartridge
    app.kubernetes.io/instance: my-cartridge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: tarantool
    app.kubernetes.io/component: tarantool
    tarantool.io/cluster-name: my-cartridge
spec:
  domain: cluster.local
  listenPort: 3301
  foreignLeader: 
  failover:
    mode: "disabled"
