---
# Source: cartridge/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-cartridge-role-storage
  labels:
    tarantool.io/service-kind: "role"
    app.kubernetes.io/name: cartridge
    app.kubernetes.io/instance: my-cartridge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: tarantool
    app.kubernetes.io/component: tarantool
    tarantool.io/cluster-name: my-cartridge
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 8081
      protocol: TCP
      name: http
      targetPort: http
    - port: 3301
      protocol: TCP
      name: tarantool-tcp
      targetPort: tarantool-tcp
    - port: 3301
      protocol: UDP
      name: tarantool-udp
      targetPort: tarantool-tcp
  selector:
    app.kubernetes.io/name: cartridge
    app.kubernetes.io/instance: my-cartridge
    app.kubernetes.io/component: tarantool
    tarantool.io/cluster-name: my-cartridge
    tarantool.io/role-name: my-cartridge-storage
---
# Source: cartridge/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-cartridge-role-router
  labels:
    tarantool.io/service-kind: "role"
    app.kubernetes.io/name: cartridge
    app.kubernetes.io/instance: my-cartridge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: tarantool
    app.kubernetes.io/component: tarantool
    tarantool.io/cluster-name: my-cartridge
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 8081
      protocol: TCP
      name: http
      targetPort: http
    - port: 3301
      protocol: TCP
      name: tarantool-tcp
      targetPort: tarantool-tcp
    - port: 3301
      protocol: UDP
      name: tarantool-udp
      targetPort: tarantool-tcp
  selector:
    app.kubernetes.io/name: cartridge
    app.kubernetes.io/instance: my-cartridge
    app.kubernetes.io/component: tarantool
    tarantool.io/cluster-name: my-cartridge
    tarantool.io/role-name: my-cartridge-router
