---
# Source: tarantool-operator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-operator-tarantool-operator
  labels:
    app.kubernetes.io/name: tarantool-operator
    app.kubernetes.io/instance: my-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: tarantool
    app.kubernetes.io/component: tarantool-operator-ce
  namespace: "default"
automountServiceAccountToken: true
