---
apiVersion: v2
name: tarantool-operator
description: Tarantool Operator
type: application
version: 1.0.1
appVersion: 1.0.0-rc2
kubeVersion: ">=1.16-0"
keywords:
  - tarantool
  - tarantool-operator
